"""Corpus calibration cross-check (R-2, doc/08 new case, L3).

Anchors the simulation's pharmacology priors against the *vendored*, live
measured corpora instead of folklore class-medians:

- ``data/benchmarks/herg_measured_nm.json`` — ChEMBL hERG (Kv11.1) IC50 rows
  for the five-benchmark corpus, regenerated by
  ``scripts/data/fetch_chembl_herg.py`` (retrieved_utc recorded in-file);
- ``data/corpora/herg_central.tsv.gz`` — the hERG Central dose-response
  corpus (Du et al., J Chem Inf Model 2022) hosted by Harvard Dataverse
  (doi:10.7910/DVN/7BVDG8, the provenance of the TDC ``Herg`` set).

Assertions (all weak upper/lower bounds, deliberately conservative):

1. the dofetilide measured central estimate is a real high-affinity blocker
   (IC50 < 100 nM),
2. the model's hERG class prior (2 nM, ``targets.py`` hERG default) is within
   a log unit and change (factor 20) of that measurement — and sits on the
   conservative (more-potent) side,
3. in the corpus, hERG blockade at 1 uM is the *exception* (median < 30 %
   inhibition) and only a thin tail of molecules reaches >= 20 % — validating
   that a dedicated per-compound hERG override (not a blanket class prior) is
   the honest modelling choice for dofetilide.
"""

from __future__ import annotations

import csv
import gzip
import json
from pathlib import Path

import numpy as np
from validation.cases.base import CaseResult, EvidenceLevel, MetricResult

_ROOT = Path(__file__).resolve().parents[2] / "data"
_MEASURED_FILE = _ROOT / "benchmarks" / "herg_measured_nm.json"
_HERG_CORPUS = _ROOT / "corpora" / "herg_central.tsv.gz"
_MODEL_HERG_KD_NM = 2.0  # targets.py hERG (Kv11.1) class prior


def _measured_dofetilide_nm() -> float:
    if not _MEASURED_FILE.exists():
        raise FileNotFoundError("vendored hERG measurement missing (data/benchmarks/)")
    try:
        payload = json.loads(_MEASURED_FILE.read_text(encoding="utf-8"))
        val = float(payload["compounds"]["dofetilide"]["ic50_geomean_nm"])
    except (ValueError, KeyError, TypeError) as exc:  # pragma: no cover - corrupt vendor
        raise RuntimeError(f"corrupt hERG measurement vendor {_MEASURED_FILE}: {exc}") from exc
    if val <= 0 or not np.isfinite(val):
        raise RuntimeError(f"non-positive hERG measurement vendor value: {val}")
    return val


def _corpus_moments() -> tuple[float, float, int]:
    if not _HERG_CORPUS.exists():
        raise FileNotFoundError("vendored hERG corpus missing (data/corpora/)")
    at_1uM: list[float] = []
    rows = 0
    with gzip.open(_HERG_CORPUS, "rt", errors="replace") as fh:
        reader = csv.reader(fh, delimiter="\t")
        next(reader, None)
        for row in reader:
            if len(row) < 3:
                continue
            rows += 1
            try:
                at_1uM.append(float(row[2]))
            except (ValueError, IndexError):
                continue
    arr = np.array(at_1uM)
    if not arr.size:
        raise RuntimeError("empty hERG corpus")
    return (float(np.percentile(arr, 50)), float(np.percentile(arr, 99.9)), rows)


def case_corpus_calibration() -> CaseResult:
    measured_nm = _measured_dofetilide_nm()
    median_1uM, p99_9_1uM, n_rows = _corpus_moments()

    ratio = _MODEL_HERG_KD_NM / measured_nm if measured_nm > 0 else float("inf")
    high_affinity_ok = measured_nm < 100.0
    prior_in_envelope_ok = 0.05 <= ratio <= 20.0
    corpus_exception_ok = median_1uM < 30.0 and 25.0 <= p99_9_1uM
    ok = high_affinity_ok and prior_in_envelope_ok and corpus_exception_ok

    metrics = [
        MetricResult(
            "dofetilide_herg_measured_geomean_nm",
            measured_nm,
            0.0,
            100.0,
            "nM",
            "pass" if high_affinity_ok else "FAIL",
        ),
        MetricResult(
            "model_prior_to_measured_ratio",
            ratio,
            0.05,
            20.0,
            "fold",
            "pass" if prior_in_envelope_ok else "FAIL",
        ),
        MetricResult(
            "herg_corpus_median_pct_inh_at_1uM",
            median_1uM,
            0.0,
            30.0,
            "% inhibition",
            "pass" if median_1uM < 30.0 else "FAIL",
        ),
        MetricResult(
            "herg_corpus_p99_9_pct_inh_at_1uM",
            p99_9_1uM,
            25.0,
            100.0,
            "% inhibition",
            "pass" if p99_9_1uM >= 25.0 else "FAIL",
        ),
    ]
    notes = [
        "dofetilide ChEMBL hERG IC50 geomean "
        f"{measured_nm:.1f} nM (core rows, outlier >=10 uM excluded; regen by "
        "scripts/data/fetch_chembl_herg.py); model class prior "
        f"{_MODEL_HERG_KD_NM} nM = {ratio:.1f}x of measured (conservative direction, "
        f"within the 20x envelope). hERG Central corpus: {n_rows} PMID-anchored "
        f"rows; median %inhibition at 1 uM = {median_1uM:.1f}, P99.9 = "
        f"{p99_9_1uM:.1f} (blockade is the exception, so a per-compound hERG "
        "override is the honest modelling choice)."
    ]
    return CaseResult(
        "Corpus calibration cross-check (R-2)",
        ok,
        metrics,
        notes,
        level=EvidenceLevel.L3_EMPIRICAL,
    )


__all__ = ["case_corpus_calibration"]
