"""Minimal typing surface for the subset of python-libsbml consumed by DrugOS.

The upstream distribution ships no type annotations; documented in
doc/06-technology-stack.md per the release quality gate (G2).  Covers the
SBML L2V4 reader used by drugos.pathway.sbml_pathway (BioModels
BIOMD0000000009).
"""

from collections.abc import Iterable, Iterator


class ReadError: ...


class SBMLErrorLog:
    def getNumErrors(self) -> int: ...


class Document:
    def getModel(self) -> Model | None: ...
    def validate(self) -> object: ...
    def getErrorLog(self) -> SBMLErrorLog: ...


class Compartment:
    def isSetSize(self) -> bool: ...
    def getSize(self) -> float: ...


class Parameter:
    def getId(self) -> str: ...
    def getValue(self) -> float: ...
    def isSetValue(self) -> bool: ...


class ListOfParameters:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Parameter: ...
    def size(self) -> int: ...
    def get(self, index: int) -> Parameter: ...


class SpeciesReference:
    def getSpecies(self) -> str: ...
    def getStoichiometry(self) -> float: ...


class ListOfSpeciesReferences(Iterable[SpeciesReference]):
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> SpeciesReference: ...
    def __iter__(self) -> Iterator[SpeciesReference]: ...
    def size(self) -> int: ...
    def get(self, index: int) -> SpeciesReference: ...


class KineticLaw:
    def getFormula(self) -> str: ...
    def isSetFormula(self) -> bool: ...
    def getListOfParameters(self) -> ListOfParameters: ...
    def getNumParameters(self) -> int: ...
    def getParameter(self, index: int) -> Parameter: ...


class Reaction:
    def getKineticLaw(self) -> KineticLaw: ...
    def getReactants(self) -> ListOfSpeciesReferences: ...
    def getProducts(self) -> ListOfSpeciesReferences: ...
    def getListOfReactants(self) -> ListOfSpeciesReferences: ...
    def getListOfProducts(self) -> ListOfSpeciesReferences: ...
    def getNumReactants(self) -> int: ...
    def getNumProducts(self) -> int: ...


class Model:
    def getName(self) -> str: ...
    def getId(self) -> str: ...
    def getNumCompartments(self) -> int: ...
    def getCompartment(self, index: int) -> Compartment: ...
    def getNumSpecies(self) -> int: ...
    def getSpecies(self, index: int) -> Species: ...
    def getNumReactions(self) -> int: ...
    def getReaction(self, index: int) -> Reaction: ...
    def getNumRules(self) -> int: ...
    def getRule(self, index: int) -> Rule: ...


class Rule:
    def getFormula(self) -> str: ...
    def getVariable(self) -> str: ...


class Species:
    def isSetInitialConcentration(self) -> bool: ...
    def getInitialConcentration(self) -> float: ...
    def getId(self) -> str: ...
    def getName(self) -> str: ...


def readSBML(path: str) -> Document: ...